CREATE DATABASE todolist;
USE todolist;

CREATE TABLE user(
	user_id VARCHAR(5) PRIMARY KEY,
	name VARCHAR(20) UNIQUE NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE todo(
	id VARCHAR(5) PRIMARY KEY,
	description VARCHAR(255) NOT NULL,
	user_id VARCHAR(5) NOT NULL,
	CONSTRAINT FOREIGN KEY(user_id) REFERENCES user(user_id)
);